version: "3.7"
services:
    db:
        image: mysql
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_HOST: localhost
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: test
        volumes:
            - ./data:/var/lib/mysql
